"""add settlement tracking fields

Revision ID: 0bc30f27d343
Revises: 34317f004643
Create Date: 2025-07-01 18:01:06.123215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc30f27d343'
down_revision = '34317f004643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arrears', schema=None) as batch_op:
        batch_op.create_index('ix_loan_schedule', ['loan_id', 'schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arrears', schema=None) as batch_op:
        batch_op.drop_index('ix_loan_schedule')

    # ### end Alembic commands ###
