"""Add written_off_amount to loan_applications

Revision ID: 0e50ef4e983a
Revises: 0bc30f27d343
Create Date: 2025-07-01 18:52:29.455181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e50ef4e983a'
down_revision = '0bc30f27d343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('written_off_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('insurance_settlement_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.drop_column('insurance_settlement_amount')
        batch_op.drop_column('written_off_amount')

    # ### end Alembic commands ###
