"""Add settlement_proof to Payment

Revision ID: 1044d62bd210
Revises: d94d181a8c2e
Create Date: 2025-05-26 21:29:41.157395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1044d62bd210'
down_revision = 'd94d181a8c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settlement_proof', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('settlement_proof')

    # ### end Alembic commands ###
