"""Make settlement_reason nullable

Revision ID: 13cdbcb18dbb
Revises: b6135235f5ff
Create Date: 2025-06-07 19:49:06.139898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cdbcb18dbb'
down_revision = 'b6135235f5ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.alter_column('settlement_reason',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')

    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.alter_column('settlement_reason',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
