"""Add monthly_budget to Agent

Revision ID: 1fe849ebfb06
Revises: a018bc8387a8
Create Date: 2025-07-28 19:19:44.814240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe849ebfb06'
down_revision = 'a018bc8387a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_budget', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('monthly_budget')

    # ### end Alembic commands ###
