"""changes to PaymentAllocation

Revision ID: 2b760c0e3015
Revises: f3cc4a904c86
Create Date: 2025-08-01 09:25:18.646910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b760c0e3015'
down_revision = 'f3cc4a904c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.alter_column('principal',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('interest',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('fees',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('fees',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('interest',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('principal',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
