"""Add is_allocated to Payment

Revision ID: 32144a25e5b4
Revises: 0e50ef4e983a
Create Date: 2025-07-12 12:00:05.270864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32144a25e5b4'
down_revision = '0e50ef4e983a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_allocated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('is_allocated')

    # ### end Alembic commands ###
