"""Remove unique constraint on payment_id in PaymentAllocation

Revision ID: 34317f004643
Revises: a96578aba1cc
Create Date: 2025-06-28 04:16:35.335568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34317f004643'
down_revision = 'a96578aba1cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payment_allocation_payment_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_payment_allocation_payment_id', ['payment_id'])

    # ### end Alembic commands ###
