"""Add region and indexes to LoanApplication

Revision ID: 3ecf8d4cde89
Revises: 4394b1e92fe3
Create Date: 2025-08-03 20:24:28.703718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ecf8d4cde89'
down_revision = '4394b1e92fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=50), nullable=True))
        batch_op.create_index('ix_loan_applications_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_loan_applications_region_category', ['region', 'category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.drop_index('ix_loan_applications_region_category')
        batch_op.drop_index('ix_loan_applications_created_at')
        batch_op.drop_column('region')

    # ### end Alembic commands ###
