"""Add indexes and employment_number to Customer

Revision ID: 4394b1e92fe3
Revises: e0f9421377ac
Create Date: 2025-08-03 06:23:19.073291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4394b1e92fe3'
down_revision = 'e0f9421377ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_number', sa.String(length=20), nullable=True))
        batch_op.create_index('idx_customers_employment_number', ['employment_number'], unique=False)
        batch_op.create_unique_constraint('uq_customers_employment_number', ['employment_number'])
        batch_op.create_unique_constraint('uq_customers_employment_number', ['employment_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_customers_employment_number', type_='unique')
        batch_op.drop_index('idx_customers_employment_number')
        batch_op.drop_column('employment_number')

    # ### end Alembic commands ###
