"""add payroll_deductions and cash_receipts

Revision ID: 63a7897b57a3
Revises: f6ffe002f368
Create Date: 2025-08-07 23:29:07.730252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a7897b57a3'
down_revision = 'f6ffe002f368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('par_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tenure', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_snapshot_composite', ['snapshot_date', 'type', 'tenure'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('par_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint('uq_snapshot_composite', type_='unique')
        batch_op.drop_column('tenure')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
