"""Add date_joined to customers

Revision ID: 6fd8934e1ded
Revises: 32144a25e5b4
Create Date: 2025-07-14 16:12:08.063348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd8934e1ded'
down_revision = '32144a25e5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
