"""Fix team_lead_id FK

Revision ID: 7c33cdc8c277
Revises: 98dd67d7afde
Create Date: 2025-07-29 13:53:50.765822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c33cdc8c277'
down_revision = '98dd67d7afde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_lead_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_agents_team_lead_id', 'agents', ['team_lead_id'], ['id'])
        batch_op.drop_column('team_lead')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_lead', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('team_lead_id')

    # ### end Alembic commands ###
