"""Add payment_frequency_months to placement

Revision ID: 83e897f708fc
Revises: ca3e1ed0a5df
Create Date: 2025-07-23 17:22:44.839489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e897f708fc'
down_revision = 'ca3e1ed0a5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_frequency_months', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')

    with op.batch_alter_table('placement', schema=None) as batch_op:
        batch_op.drop_column('payment_frequency_months')

    # ### end Alembic commands ###
