"""Add principal_due and total_due to PlacementSchedule

Revision ID: 9ad395383038
Revises: 83e897f708fc
Create Date: 2025-07-23 18:51:59.923539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad395383038'
down_revision = '83e897f708fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal_due', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_due', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_schedule', schema=None) as batch_op:
        batch_op.drop_column('total_due')
        batch_op.drop_column('principal_due')

    # ### end Alembic commands ###
