"""Add date_joined to Customer

Revision ID: a96578aba1cc
Revises: 93ec6b3d48c8
Create Date: 2025-06-28 02:58:06.660876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96578aba1cc'
down_revision = '93ec6b3d48c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_date_joined'), ['date_joined'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_date_joined'))
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###
