"""removed duplicated status in repayment schedule

Revision ID: c1f164386087
Revises: 63a7897b57a3
Create Date: 2025-08-08 09:40:07.501097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f164386087'
down_revision = '63a7897b57a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('deduction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('par_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint('uq_snapshot_composite', type_='unique')
        batch_op.drop_column('type')
        batch_op.drop_column('tenure')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('par_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenure', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.INTEGER(), nullable=True))
        batch_op.create_unique_constraint('uq_snapshot_composite', ['snapshot_date', 'type', 'tenure'])

    op.drop_table('payroll_deductions')
    op.drop_table('cash_receipts')
    # ### end Alembic commands ###
