"""Add indexes to Customer and LoanApplication

Revision ID: e0f9421377ac
Revises: 2b760c0e3015
Create Date: 2025-08-03 06:07:13.119053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f9421377ac'
down_revision = '2b760c0e3015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('idx_customers_agent_id', ['agent_id'], unique=False)
        batch_op.create_index('idx_customers_file_number', ['file_number'], unique=False)
        batch_op.create_index('idx_customers_national_id', ['national_id'], unique=False)
        batch_op.create_unique_constraint('uq_customers_file_number', ['file_number'])
        batch_op.create_unique_constraint('uq_customers_national_id', ['national_id'])

    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.create_index('idx_loan_applications_agent_id', ['agent_id'], unique=False)
        batch_op.create_index('idx_loan_applications_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('idx_loan_applications_loan_number', ['loan_number'], unique=False)
        batch_op.create_unique_constraint('uq_loan_applications_loan_number', ['loan_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_loan_applications_loan_number', type_='unique')
        batch_op.drop_index('idx_loan_applications_loan_number')
        batch_op.drop_index('idx_loan_applications_customer_id')
        batch_op.drop_index('idx_loan_applications_agent_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customers_national_id', type_='unique')
        batch_op.drop_constraint('uq_customers_file_number', type_='unique')
        batch_op.drop_index('idx_customers_national_id')
        batch_op.drop_index('idx_customers_file_number')
        batch_op.drop_index('idx_customers_agent_id')

    # ### end Alembic commands ###
