"""Final Agent model fix

Revision ID: e8ce5a297e2e
Revises: cc9faea37df7
Create Date: 2025-07-30 15:56:17.742999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ce5a297e2e'
down_revision = 'cc9faea37df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agents_team_lead_id', type_='foreignkey')
        batch_op.drop_column('team_lead_id')
        batch_op.add_column(sa.Column('team_leader_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_agents_team_leader_id',
            'agents',
            ['team_leader_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_lead_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_agents_team_lead_id', 'agents', ['team_lead_id'], ['id'])
        batch_op.drop_column('team_leader_id')

    # ### end Alembic commands ###
