"""Add top_up_interest to PaymentAllocation

Revision ID: f3cc4a904c86
Revises: de7ec461a92c
Create Date: 2025-08-01 08:27:51.297112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cc4a904c86'
down_revision = 'de7ec461a92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top_up_interest', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_column('top_up_interest')

    # ### end Alembic commands ###
