"""Add changes to notifications model

Revision ID: f6ffe002f368
Revises: 3ecf8d4cde89
Create Date: 2025-08-03 21:31:12.471359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ffe002f368'
down_revision = '3ecf8d4cde89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_recipients', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email_subject', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('email_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('sent_at')
        batch_op.drop_column('email_sent')
        batch_op.drop_column('email_content')
        batch_op.drop_column('email_subject')
        batch_op.drop_column('email_recipients')

    # ### end Alembic commands ###
